In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("D:/College Practicals/DSBDA Practical Final/Iris.csv")

In [3]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [6]:
grouped = df.groupby('Species')

In [10]:
summary = grouped['SepalLengthCm'].agg(['mean','median','min','max','std'])
summary

                  mean  median  min  max       std
Species
Iris-setosa      5.006     5.0  4.3  5.8  0.352490
Iris-versicolor  5.936     5.9  4.9  7.0  0.516171
Iris-virginica   6.588     6.5  4.9  7.9  0.635880

In [11]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [12]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [16]:
setosa_list = df[ df['Species'] == 'Iris-setosa' ]['SepalLengthCm'].to_list()
versicolor_list = df[ df['Species'] == 'Iris-versicolor' ]['SepalLengthCm'].to_list()
virginica_list = df[ df['Species'] == 'Iris-virginica' ]['SepalLengthCm'].to_list()

print('\nSetosa List : ', setosa_list )
print('\nVersicolor List : ', versicolor_list )
print('\nVirginica List : ', virginica_list )

Setosa List :  [5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, 4.9, 5.4, 4.8, 4.8, 4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5.0, 5.0, 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5.0, 5.5, 4.9, 4.4, 5.1, 5.0, 4.5, 4.4, 5.0, 5.1, 4.8, 5.1, 4.6, 5.3, 5.0]

Versicolor List :  [7.0, 6.4, 6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5.0, 5.9, 6.0, 6.1, 5.6, 6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7, 6.0, 5.7, 5.5, 5.5, 5.8, 6.0, 5.4, 6.0, 6.7, 6.3, 5.6, 5.5, 5.5, 6.1, 5.8, 5.0, 5.6, 5.7, 5.7, 6.2, 5.1, 5.7]

Virginica List :  [6.3, 5.8, 7.1, 6.3, 6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5, 7.7, 7.7, 6.0, 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2, 7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6.0, 6.9, 6.7, 6.9, 5.8, 6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9]

In [17]:
setosa = df[ df['Species'] == 'Iris-setosa' ]
versicolor = df[ df['Species'] == 'Iris-versicolor' ]
virginica = df[ df['Species'] == 'Iris-virginica' ]

In [26]:
def display_stats(name,data):
    print(f'\n {name} Statistics : ')
    print('\nMean : ',data.mean( numeric_only=True) )
    print('\nMedian : ',data.median(numeric_only=True) )
    print('\nStandard Deviation : ',data.std(numeric_only=True) )   
    print('\nPercentiles :\n', data.quantile([0.25,0.50,0.75],numeric_only=True) )

In [28]:
display_stats('Setosa', setosa)
display_stats('Versicolor', versicolor)
display_stats('Virginica', virginica)

 Setosa Statistics :

Mean :  Id               25.500
SepalLengthCm     5.006
SepalWidthCm      3.418
PetalLengthCm     1.464
PetalWidthCm      0.244
dtype: float64

Median :  Id               25.5
SepalLengthCm     5.0
SepalWidthCm      3.4
PetalLengthCm     1.5
PetalWidthCm      0.2
dtype: float64

Standard Deviation :  Id               14.577380
SepalLengthCm     0.352490
SepalWidthCm      0.381024
PetalLengthCm     0.173511
PetalWidthCm      0.107210
dtype: float64

Percentiles :
          Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0.25  13.25            4.8         3.125          1.400           0.2
0.50  25.50            5.0         3.400          1.500           0.2
0.75  37.75            5.2         3.675          1.575           0.3

 Versicolor Statistics :

Mean :  Id               75.500
SepalLengthCm     5.936
SepalWidthCm      2.770
PetalLengthCm     4.260
PetalWidthCm      1.326
dtype: float64

Median :  Id               75.50
SepalLengthCm     5.90
SepalWidthCm      2.80
PetalLengthCm     4.35
PetalWidthCm      1.30
dtype: float64

Standard Deviation :  Id               14.577380
SepalLengthCm     0.516171
SepalWidthCm      0.313798
PetalLengthCm     0.469911
PetalWidthCm      0.197753
dtype: float64

Percentiles :
          Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0.25  63.25            5.6         2.525           4.00           1.2
0.50  75.50            5.9         2.800           4.35           1.3
0.75  87.75            6.3         3.000           4.60           1.5

 Virginica Statistics :

Mean :  Id               125.500
SepalLengthCm      6.588
SepalWidthCm       2.974
PetalLengthCm      5.552
PetalWidthCm       2.026
dtype: float64

Median :  Id               125.50
SepalLengthCm      6.50
SepalWidthCm       3.00
PetalLengthCm      5.55
PetalWidthCm       2.00
dtype: float64

Standard Deviation :  Id               14.577380
SepalLengthCm     0.635880
SepalWidthCm      0.322497
PetalLengthCm     0.551895
PetalWidthCm      0.274650
dtype: float64

Percentiles :
           Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0.25  113.25          6.225         2.800          5.100           1.8
0.50  125.50          6.500         3.000          5.550           2.0
0.75  137.75          6.900         3.175          5.875           2.3

In [29]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica